In [1]:
import pandas as pd
import numpy as np

In [2]:
nfl_data = pd.read_csv('NFL Play by Play 2009-2017 (v4).csv')
nfl_data

C:\Users\Arjun Janamatti\Anaconda3\envs\tf_nptel\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (25,51) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407683,2017-12-31,2017123101,29,4,NaN,00:28,1,28.0,4.0,BAL,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,2017
407684,2017-12-31,2017123101,29,4,3.0,00:28,1,28.0,0.0,BAL,...,-0.397515,0.080409,0.919591,0.050478,0.949522,0.080409,-0.029931,-0.021795,-0.008136,2017
407685,2017-12-31,2017123101,29,4,4.0,00:24,1,24.0,4.0,BAL,...,2.457114,0.050478,0.949522,0.030881,0.969119,0.050478,-0.019597,-0.030603,0.011006,2017
407686,2017-12-31,2017123101,30,4,1.0,00:14,1,14.0,10.0,BAL,...,NaN,0.030881,0.969119,0.000000,1.000000,0.969119,0.030881,NaN,NaN,2017
407687,2017-12-31,2017123101,30,4,NaN,00:00,0,0.0,14.0,BAL,...,NaN,0.000000,1.000000,0.000000,1.000000,0.999159,0.000000,NaN,NaN,2017

### How many missing values?

In [11]:
missing_value_count = nfl_data.isna().sum()
column_names = list(nfl_data.columns)
[(column_names[index], value) for index, value in enumerate(missing_value_count) if value>0]

[('down', 61154),
 ('time', 224),
 ('TimeSecs', 224),
 ('PlayTimeDiff', 444),
 ('SideofField', 528),
 ('yrdln', 840),
 ('yrdline100', 840),
 ('GoalToGo', 840),
 ('FirstDown', 28811),
 ('posteam', 24992),
 ('DefensiveTeam', 24992),
 ('desc', 2),
 ('ExPointResult', 397578),
 ('TwoPointConv', 407083),
 ('DefTwoPoint', 407664),
 ('PuntResult', 385317),
 ('Passer', 240045),
 ('PassOutcome', 239506),
 ('PassLength', 240520),
 ('PassLocation', 240520),
 ('Interceptor', 403168),
 ('Rusher', 287124),
 ('RunLocation', 288178),
 ('RunGap', 320260),
 ('Receiver', 246127),
 ('ReturnResult', 389450),
 ('Returner', 382384),
 ('BlockingPlayer', 407571),
 ('Tackler1', 166134),
 ('Tackler2', 357953),
 ('FieldGoalResult', 398629),
 ('FieldGoalDistance', 398740),
 ('RecFumbTeam', 403315),
 ('RecFumbPlayer', 403315),
 ('ChalReplayResult', 404286),
 ('PenalizedTeam', 378189),
 ('PenaltyType', 391261),
 ('PenalizedPlayer', 379403),
 ('PosTeamScore', 26904),
 ('DefTeamScore', 26904),
 ('ScoreDiff', 24988),
 ('AbsScoreDiff', 26904),
 ('No_Score_Prob', 176),
 ('Opp_Field_Goal_Prob', 176),
 ('Opp_Safety_Prob', 176),
 ('Opp_Touchdown_Prob', 176),
 ('Field_Goal_Prob', 176),
 ('Safety_Prob', 176),
 ('Touchdown_Prob', 176),
 ('ExpPts', 176),
 ('EPA', 369),
 ('airEPA', 248394),
 ('yacEPA', 248498),
 ('Home_WP_pre', 24954),
 ('Away_WP_pre', 24954),
 ('Home_WP_post', 26587),
 ('Away_WP_post', 26587),
 ('Win_Prob', 25009),
 ('WPA', 5541),
 ('airWPA', 248501),
 ('yacWPA', 248762)]

### Percentage of missing values in each column, when compared to total values

In [12]:
[(column_names[index], round(((value/len(nfl_data))*100),2)) for index, value in enumerate(missing_value_count) if value>0]

[('down', 15.0),
 ('time', 0.05),
 ('TimeSecs', 0.05),
 ('PlayTimeDiff', 0.11),
 ('SideofField', 0.13),
 ('yrdln', 0.21),
 ('yrdline100', 0.21),
 ('GoalToGo', 0.21),
 ('FirstDown', 7.07),
 ('posteam', 6.13),
 ('DefensiveTeam', 6.13),
 ('desc', 0.0),
 ('ExPointResult', 97.52),
 ('TwoPointConv', 99.85),
 ('DefTwoPoint', 99.99),
 ('PuntResult', 94.51),
 ('Passer', 58.88),
 ('PassOutcome', 58.75),
 ('PassLength', 59.0),
 ('PassLocation', 59.0),
 ('Interceptor', 98.89),
 ('Rusher', 70.43),
 ('RunLocation', 70.69),
 ('RunGap', 78.56),
 ('Receiver', 60.37),
 ('ReturnResult', 95.53),
 ('Returner', 93.79),
 ('BlockingPlayer', 99.97),
 ('Tackler1', 40.75),
 ('Tackler2', 87.8),
 ('FieldGoalResult', 97.78),
 ('FieldGoalDistance', 97.81),
 ('RecFumbTeam', 98.93),
 ('RecFumbPlayer', 98.93),
 ('ChalReplayResult', 99.17),
 ('PenalizedTeam', 92.76),
 ('PenaltyType', 95.97),
 ('PenalizedPlayer', 93.06),
 ('PosTeamScore', 6.6),
 ('DefTeamScore', 6.6),
 ('ScoreDiff', 6.13),
 ('AbsScoreDiff', 6.6),
 ('No_Score_Prob', 0.04),
 ('Opp_Field_Goal_Prob', 0.04),
 ('Opp_Safety_Prob', 0.04),
 ('Opp_Touchdown_Prob', 0.04),
 ('Field_Goal_Prob', 0.04),
 ('Safety_Prob', 0.04),
 ('Touchdown_Prob', 0.04),
 ('ExpPts', 0.04),
 ('EPA', 0.09),
 ('airEPA', 60.93),
 ('yacEPA', 60.95),
 ('Home_WP_pre', 6.12),
 ('Away_WP_pre', 6.12),
 ('Home_WP_post', 6.52),
 ('Away_WP_post', 6.52),
 ('Win_Prob', 6.13),
 ('WPA', 1.36),
 ('airWPA', 60.95),
 ('yacWPA', 61.02)]

### Percentage of missing values from total dataframe

In [16]:
total_cells = nfl_data.size
print('Total cells in the dataframe: ', total_cells)
total_missing = missing_value_count.sum()
print('Total missing values in dataframe: ', total_missing)
percent_missing = round(((total_missing/total_cells) * 100), 2)
print('Percentage of values missing in dataframe: ',percent_missing)

Total cells in the dataframe:  41584176
Total missing values in dataframe:  10342875
Percentage of values missing in dataframe:  24.87

### Is this value missing because it wasn't recorded or because it doesn't exist?
If a value is missing becuase it doesn't exist (like the height of the oldest child of someone who doesn't have any children) then it doesn't make sense to try and guess what it might be. These values you probably do want to keep as NaN. On the other hand, if a value is missing because it wasn't recorded, then you can try to guess what it might have been based on the other values in that column and row. This is called __imputation__.

"TimesSec" has a lot of missing values in it. By looking at the documentation, I can see that this column has information on the number of seconds left in the game when the play was made. This means that these values are probably missing because they were not recorded, rather than because they don't exist. So, it would make sense for us to try and guess what they should be rather than just leaving them as NA's.

On the other hand, there are other fields, like "PenalizedTeam" that also have lot of missing fields. In this case, though, the field is missing because if there was no penalty then it doesn't make sense to say which team was penalized. For this column, it would make more sense to either leave it empty or to add a third value like "neither" and use that to replace the NA's.

### Drop all values

In [17]:
nfl_data_drop_all_na_values = nfl_data.dropna()
nfl_data_drop_all_na_values

Empty DataFrame
Columns: [Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, PlayTimeDiff, SideofField, yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, desc, PlayAttempted, Yards.Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Safety, Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength, AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher, Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult, Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble, RecFumbTeam, RecFumbPlayer, Sack, Challenge.Replay, ChalReplayResult, Accepted.Penalty, PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty.Yards, PosTeamScore, DefTeamScore, ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team, posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre, HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, ...]
Index: []

[0 rows x 102 columns]

### Remove columns which have at least one null value

In [19]:
nfl_data_columns_na_drop = nfl_data.dropna(axis = 1)
nfl_data_columns_na_drop

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407683,2017-12-31,2017123101,29,4,1,0,-4,1,0,0,...,1,BAL,0,3,0,2,0,0.0,0.0,2017
407684,2017-12-31,2017123101,29,4,1,14,-4,1,0,0,...,0,None,2,2,0,2,0,0.0,0.0,2017
407685,2017-12-31,2017123101,29,4,1,14,9,1,13,0,...,0,None,2,2,0,2,0,0.0,0.0,2017
407686,2017-12-31,2017123101,30,4,1,10,-1,1,-1,0,...,0,None,0,2,0,2,0,0.0,0.0,2017
407687,2017-12-31,2017123101,30,4,0,0,-1,1,0,0,...,0,None,0,2,0,2,0,0.0,0.0,2017

### Filling in missing values automatically

In [20]:
subset_nfl_data = nfl_data.loc[:, 'EPA':'Season'].head()
subset_nfl_data

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,NaN,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,NaN,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,NaN,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

We can use the Panda's fillna() function to fill in missing values in a dataframe for us. One option we have is to specify what we want the NaN values to be replaced with. Here, I'm saying that I would like to replace all the NaN values with 0.

In [21]:
# replace all NA's with 0
subset_nfl_data.fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,0.000000,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,0.000000,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009

I could also be a bit more savvy and replace missing values with whatever value comes directly after it in the same column. (This makes a lot of sense for datasets where the observations have some sort of logical order to them.)

In [24]:
# replace all NA's the value that comes directly after it in the same column, 
# then replace all the remaining na's with 0
subset_nfl_data.fillna(method='bfill', axis=0).fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,-1.068169,1.146076,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,-0.032244,0.036899,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,3.318841,-5.031425,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.106663,-0.156239,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009